// produtos
###
POST http://localhost:3333/produtos
Content-Type: application/json

{
    "nome": "Brigadeiro Gourmet",
    "descricao": "Brigadeiro top",
    "preco": 5,
    "tipo_de_medida": "Unidade",
    "ingredientes":"chocolate, leite condensado, manteiga"
}
###

GET http://localhost:3333/produtos?search=Brigadeiro

###

PUT  http://localhost:3333/produtos/3
Content-Type: application/json

{
    "nome": "Brigadeiro de Ninho Gourmet",
    "descricao": "Brigadeiro top",
    "preco": 7,
    "tipo_de_medida": "Unidade",
    "ingredientes":"chocolate, leite condensado, manteiga"
}

###

DELETE http://localhost:3333/produtos/2
###


// auth
POST http://localhost:3333/auth/user
Content-Type: application/json

{
    "nome": "leonardo",
    "email": "teste@teste.com",
    "senha": "1234",
    "tipo_acesso": "1"
}
###

GET http://localhost:3333/auth/user
###

PUT  http://localhost:3333/auth/user/1
Content-Type: application/json

{
    "nome": "leonardo hehe",
    "email": "teste@teste.com",
    "senha": "1234",
    "tipo_acesso": "1"
}

###

DELETE http://localhost:3333/auth/user/1
###